### ISSUE TITLE
Trigger re-rendering dynamically?

### ISSUE THREAD

**Issue by SantoJambit** [FlorianRappl/parcel-plugin-codegen#2]
Just playing with this plugin a bit to generate content based on all files found in a specified folder.
But when a new file gets created, the code needs to be regenerated. Is there any way to do this aside from touching the codegen file?

**Comment by FlorianRappl** [comment]
Yeah we got some mechanism in there, however, it only works for files already present (via `this,addDependency`). We use this implicitly if you go over `this.getFiles`.

Maybe we should add something like a `watchFile` in addition, which works even if the file is not there yet.

Keeping this open as an improvement.

**Comment by TheComputerM** [comment]
Changing the file extension from `.codegen` to `.codegen.js` might solve the problem.

**Comment by FlorianRappl** [comment]
Can you elaborate @TheComputerM ?

We only register `.codegen` for the plugin. Parcel uses an extension comparison, which afaik stops at the last `.`, i.e., `foo.codegen.js` would be `.js` and thus not use this plugin.

**Comment by TheComputerM** [comment]
There are going to be [Transforms](https://github.com/parcel-bundler/parcel/tree/v2#transformers) in Parcel v2 which you can take advantage of.

**Comment by FlorianRappl** [comment]
Yep Parcel v2 will be awesome. Thanks for the pointer @TheComputerM. But is there anything in the context of v1 that we can use?

**Comment by TheComputerM** [comment]
I do not think there is
